import turtle
from random import randint
def C(x,y):
    turtle.pensize(10)
    turtle.pencolor("red")
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.right(180)
    turtle.pendown()
    turtle.circle(50, 200)
def M(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.down()
    turtle.right(110)
    turtle.forward(100)
    turtle.goto(x,y)
    turtle.left(40)
    turtle.forward(60)
    turtle.left(110)
    turtle.forward(60)
    turtle.right(145)
    turtle.forward(100)
def eight(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.down()
    turtle.circle(30)
    turtle.penup()
    turtle.goto(x+30,y-30)
    turtle.pendown()
    turtle.down()
    turtle.right(80)
    turtle.circle(30)
def three(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.down()
    turtle.right(70)
    turtle.circle(35, -200)
    turtle.left(15)
    turtle.circle(-35, 200)
def gach(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.down()
    turtle.left(60)
    turtle.forward(130)
def flower():
    turtle.penup()
    turtle.goto(0, -150)

    turtle.left(180)
    turtle.color('red', 'pink')
    turtle.pendown()
    turtle.begin_fill()
    turtle.left(150)
    turtle.circle(200, 30)
    turtle.right(45)
    turtle.circle(-5, 90)
    turtle.circle(3, 100)
    turtle.circle(-5, 90)
    turtle.circle(-20, 15)
    turtle.circle(-50, 10)
    turtle.circle(3, 90)
    turtle.circle(-10, 90)
    turtle.left(120)

    turtle.forward(30)
    turtle.right(170)
    turtle.forward(10)
    turtle.circle(2, 120)
    turtle.forward(15)
    turtle.circle(-1, 150)
    turtle.forward(5)
    turtle.circle(3, 120)
    turtle.forward(20)
    turtle.circle(-5, 90)
    turtle.forward(10)
    turtle.circle(3, 120)
    turtle.forward(8)
    turtle.circle(-5, 90)
    turtle.forward(5)
    turtle.circle(20, 20)
    turtle.forward(5)

    turtle.right(80)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(35)
    turtle.right(30)
    turtle.forward(5)
    turtle.circle(-10, 120)
    turtle.forward(3)
    turtle.circle(5, 100)
    turtle.circle(-20, 30)
    turtle.circle(-5, 60)
    turtle.forward(2)
    turtle.circle(2, 90)
    turtle.forward(2)
    turtle.circle(-10, 90)
    turtle.circle(-50, 15)
    turtle.circle(10, 60)
    turtle.forward(5)
    turtle.circle(-5, 60)
    turtle.forward(8)
    turtle.circle(10, 60)

    turtle.right(140)
    turtle.forward(50)
    turtle.left(180)
    turtle.forward(60)
    turtle.right(150)
    turtle.forward(2)
    turtle.circle(2, 120)
    turtle.forward(3)
    turtle.circle(-3, 120)
    turtle.forward(2)
    turtle.circle(4, 120)
    turtle.forward(6)
    turtle.circle(-4, 120)
    turtle.forward(3)
    turtle.circle(2, 120)
    turtle.forward(3)
    turtle.circle(-2, 120)
    turtle.forward(4)
    turtle.circle(4, 120)
    turtle.forward(8)
    turtle.circle(-5, 120)
    turtle.circle(50, 15)
    turtle.circle(5, 120)
    turtle.circle(-5, 60)

    turtle.right(120)
    turtle.forward(100)
    turtle.backward(70)
    turtle.left(150)
    turtle.forward(8)
    turtle.circle(-6, 120)
    turtle.forward(4)
    turtle.circle(5, 120)
    turtle.forward(8)
    turtle.circle(-3, 120)
    turtle.forward(3)
    turtle.circle(8, 100)
    turtle.forward(2)
    turtle.right(140)
    turtle.forward(25)

    turtle.left(110)
    turtle.circle(-50, 15)
    turtle.right(100)
    turtle.circle(200, 15)
    turtle.circle(-200, 15)
    turtle.circle(-30, 60)
    turtle.end_fill()
    turtle.left(10)
    turtle.forward(10)
    turtle.right(180)
    turtle.circle(20, 90)
    turtle.forward(50)
    turtle.circle(-200, 20)
    turtle.left(150)
    turtle.forward(3)
    turtle.circle(-3, 100)
    turtle.forward(5)
    turtle.circle(7, 100)
    turtle.forward(15)
    turtle.circle(-5, 90)
    turtle.left(110)
    turtle.circle(120, 15)
    turtle.left(20)
    turtle.forward(110)
    turtle.left(180)
    turtle.forward(115)
    turtle.circle(10, 120)
    turtle.forward(10)
    turtle.circle(-5, 120)
    turtle.circle(2, 90)
    turtle.circle(20, 30)
    turtle.circle(-3, 90)
    turtle.forward(3)
    turtle.circle(3, 120)
    turtle.forward(5)
    turtle.circle(-5, 120)
    turtle.circle(2, 120)
    turtle.forward(10)
    turtle.circle(-5, 120)
    turtle.forward(3)
    turtle.left(155)
    turtle.circle(250, 30)

    turtle.color('red', 'green')
    turtle.begin_fill()
    turtle.left(80)
    turtle.forward(15)
    turtle.circle(-20, 60)
    turtle.circle(5, 60)
    turtle.forward(10)
    turtle.circle(-15, 60)
    turtle.forward(2)
    turtle.circle(10, 60)
    turtle.forward(10)
    turtle.right(120)
    turtle.circle(-100, 30)
    turtle.right(35)
    turtle.circle(-100, 30)
    turtle.right(35)
    turtle.circle(-100, 30)
    turtle.forward(3)
    turtle.right(150)
    turtle.forward(4)
    turtle.circle(10, 120)
    turtle.end_fill()

a=input("Nhập ngày: ")
from time import sleep
if a=="8/3":
    sleep(0.3)
    print("####################################################################################################################################")
    print("#                                                                                                                                  #");sleep(0.3)
    print("#                                                                                          $                                       #");sleep(0.3)
    print("#                                                               $                            $                                     #");sleep(0.3)
    print("#                                                              $                                $                                  #");sleep(0.3)
    print("#                 $ $                       $$$$$$$  $   $  $     $  $$$$$$     $     $  $     $  $   $   $$$$                     #");sleep(0.3)
    print("#                 $ $                       $        $   $  $     $  $          $$   $$  $     $  $$  $  $                         #");sleep(0.3)
    print("#                 $ $                       $        $$$$$  $     $  $          $ $ $ $  $     $  $ $ $  $  $$$$$                  #");sleep(0.3)
    print("#                 $ $                       $        $   $  $     $  $          $  $  $  $     $  $  $$  $    $                    #");sleep(0.3)
    print("#                 $ $                       $$$$$$$  $   $  $$$$$$$  $$$$$$     $     $  $$$$$$$  $   $  $$$$$$                    #");sleep(0.3)
    print("#               $$$$$$$                                                                                                            #");sleep(0.3)
    print("#               $     $                                                                                                            #");sleep(0.3)
    print("#            $$$$$$$$$$$$                                                                                                          #");sleep(0.3)
    print("#            $          $                                   *******              *      *******                                    #");sleep(0.3)
    print("#       $$$$$$$$$$$$$$$$$$$$$$                              *     *             *             *                                    #");sleep(0.3)
    print("#       $                    $                              *     *            *              *                                    #");sleep(0.3)
    print("#       $                    $                              *******           *         *******                                    #");sleep(0.3)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          *     *          *                *                                    #");sleep(0.3)
    print("#    $                           $                          *     *         *                 *                                    #");sleep(0.3)
    print("#    $          ^_____^          $                          *******        *            *******                                    #");sleep(0.3)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                                                                                 #");sleep(0.3)
    print("#                                                                                                                                  #");sleep(0.3)
    print("#                                                                                                                                  #");sleep(0.3)
    print("#                                                                                                                                  #");sleep(0.3)
    print("#                                                                \/   \/                                                           #");sleep(0.3)
    print("#                                                                $     $                                                           #");sleep(0.3)
    print("#                                                                $     $                                                           #");sleep(0.3)
    print("#                                                                $     $                                                           #");sleep(0.3)
    print("#                                                       $$$$$$$$$$$$$$$$$$$$$$                                                     #");sleep(0.3)
    print("#                                                      $         $     $    $$                                                     #");sleep(0.3)
    print("#                                                     $$$$$$$              $$$$$$$$                                                #");sleep(0.3)
    print("#                                                    $$     $$$$$$$$$$$$$$$$     $$                                                #");sleep(0.3)
    print("#                                                    $$                          $$                                                #");sleep(0.3)
    print("#                                                    $$                          $$                                                #");sleep(0.3)
    print("#                                                    $$    o(*≧▽≦)ツ┏━┓         $$                                                #");sleep(0.3)
    print("#                                                $$$ $$                          $$$$$$                                            #");sleep(0.3)
    print("#                                           $$$$$    $$                          $$   $$$                                          #");sleep(0.3)
    print("#                                          $$    $$$$$$$                               $$                                          #");sleep(0.3)
    print("#                                          $$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                         #");sleep(0.3)
    print("#                                          $$                                           $$$                                        #");sleep(0.3)
    print("#                                          $$                                           $$$                                        #");sleep(0.3)
    print("#                                          $$        ☆*: *｡* o(≧▽≦)o *｡*:*☆           $$$                                        #");sleep(0.3)
    print("#                                          $$$                                          $$$                                        #");sleep(0.3)
    print("#                                          $$$                                         $$$$                                        #");sleep(0.3)
    print("#                                          $$$                                         $$$$                                        #");sleep(0.3)
    print("#                                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                          #");sleep(0.3)                                       #");sleep(0.3)
    print("#                                                                                                                                  #");sleep(0.3)  
    print("#####################################################################################################################################");sleep(0.3)

    a=turtle.Screen()
    a.setup(width=1.0,height=1.0,startx=None,starty=None)
    C(-150,150)
    M(-100,150)
    eight(0,130)
    gach(130,160)
    three(180,160)
    flower()
    a.bgcolor("#942727")
    meow = turtle.Turtle()
    meow.color("#660000")
    meow.speed(0)
    meow.up()
    meow.down()
    for i in range (60):
        meow.circle(300,20,5)
        meow.lt(520)
        meow.circle(300,20,5)
        meow.rt(160)
        meow.rt(270)    
        turtle.colormode(255) 
    for i in range(0,300):
        meow.color(randint(0, 255),randint(0, 255),randint(0, 255))
        meow.begin_fill()
        meow.fd(150)
        meow.rt(90)
        meow.fd(150)
        meow.rt(90)
        meow.fd(150)
        meow.rt(90)
        meow.fd(150)
        meow.end_fill()
        meow.penup()
        meow.goto(randint(-600,1500), randint(-300,300))
        meow.pendown()
    a.mainloop()
