import turtle

def flower():
    #Flower
    turtle.penup()
    turtle.goto(0, -150)

    turtle.left(90-0-90)
    turtle.color('red', 'pink')
    turtle.pendown()
    turtle.begin_fill()
    turtle.left(150)
    turtle.circle(200, 30)
    turtle.right(45)
    turtle.circle(-5, 90)
    turtle.circle(3, 100)
    turtle.circle(-5, 90)
    turtle.circle(-20, 15)
    turtle.circle(-50, 10)
    turtle.circle(3, 90)
    turtle.circle(-10, 90)
    turtle.left(120)

    turtle.forward(30)
    turtle.right(170)
    turtle.forward(10)
    turtle.circle(2, 120)
    turtle.forward(15)
    turtle.circle(-1, 150)
    turtle.forward(5)
    turtle.circle(3, 120)
    turtle.forward(20)
    turtle.circle(-5, 90)
    turtle.forward(10)
    turtle.circle(3, 120)
    turtle.forward(8)
    turtle.circle(-5, 90)
    turtle.forward(5)
    turtle.circle(20, 20)
    turtle.forward(5)

    turtle.right(80)
    turtle.forward(40)
    turtle.right(180)
    turtle.forward(35)
    turtle.right(30)
    turtle.forward(5)
    turtle.circle(-10, 120)
    turtle.forward(3)
    turtle.circle(5, 100)
    turtle.circle(-20, 30)
    turtle.circle(-5, 60)
    turtle.forward(2)
    turtle.circle(2, 90)
    turtle.forward(2)
    turtle.circle(-10, 90)
    turtle.circle(-50, 15)
    turtle.circle(10, 60)
    turtle.forward(5)
    turtle.circle(-5, 60)
    turtle.forward(8)
    turtle.circle(10, 60)

    turtle.right(140)
    turtle.forward(50)
    turtle.left(180)
    turtle.forward(60)
    turtle.right(150)
    turtle.forward(2)
    turtle.circle(2, 120)
    turtle.forward(3)
    turtle.circle(-3, 120)
    turtle.forward(2)
    turtle.circle(4, 120)
    turtle.forward(6)
    turtle.circle(-4, 120)
    turtle.forward(3)
    turtle.circle(2, 120)
    turtle.forward(3)
    turtle.circle(-2, 120)
    turtle.forward(4)
    turtle.circle(4, 120)
    turtle.forward(8)
    turtle.circle(-5, 120)
    turtle.circle(50, 15)
    turtle.circle(5, 120)
    turtle.circle(-5, 60)

    turtle.right(120)
    turtle.forward(100)
    turtle.backward(70)
    turtle.left(150)
    turtle.forward(8)
    turtle.circle(-6, 120)
    turtle.forward(4)
    turtle.circle(5, 120)
    turtle.forward(8)
    turtle.circle(-3, 120)
    turtle.forward(3)
    turtle.circle(8, 100)
    turtle.forward(2)
    turtle.right(140)
    turtle.forward(25)

    turtle.left(110)
    turtle.circle(-50, 15)
    turtle.right(100)
    turtle.circle(200, 15)
    turtle.circle(-200, 15)
    turtle.circle(-30, 60)
    turtle.end_fill()
    turtle.left(10)
    turtle.forward(10)
    turtle.right(180)
    turtle.circle(20, 90)
    turtle.forward(50)
    turtle.circle(-200, 20)
    turtle.left(150)
    turtle.forward(3)
    turtle.circle(-3, 100)
    turtle.forward(5)
    turtle.circle(7, 100)
    turtle.forward(15)
    turtle.circle(-5, 90)
    turtle.left(110)
    turtle.circle(120, 15)
    turtle.left(20)
    turtle.forward(110)
    turtle.left(180)
    turtle.forward(115)
    turtle.circle(10, 120)
    turtle.forward(10)
    turtle.circle(-5, 120)
    turtle.circle(2, 90)
    turtle.circle(20, 30)
    turtle.circle(-3, 90)
    turtle.forward(3)
    turtle.circle(3, 120)
    turtle.forward(5)
    turtle.circle(-5, 120)
    turtle.circle(2, 120)
    turtle.forward(10)
    turtle.circle(-5, 120)
    turtle.forward(3)
    turtle.left(155)
    turtle.circle(250, 30)

    turtle.color('red', 'green')
    turtle.begin_fill()
    turtle.left(80)
    turtle.forward(15)
    turtle.circle(-20, 60)
    turtle.circle(5, 60)
    turtle.forward(10)
    turtle.circle(-15, 60)
    turtle.forward(2)
    turtle.circle(10, 60)
    turtle.forward(10)
    turtle.right(120)
    turtle.circle(-100, 30)
    turtle.right(35)
    turtle.circle(-100, 30)
    turtle.right(35)
    turtle.circle(-100, 30)
    turtle.forward(3)
    turtle.right(150)
    turtle.forward(4)
    turtle.circle(10, 120)
    turtle.end_fill()
    turtle.hideturtle()
    turtle.done()
a=input("Nhập ngày: ")
from time import sleep
if a=="8/3":
    sleep(0.5)
    print("####################################################################################################################################")
    print("#                                                                                                                                  #");sleep(0.5)
    print("#                                                                                          $                                       #");sleep(0.5)
    print("#                                                               $                            $                                     #");sleep(0.5)
    print("#                                                              $                                $                                  #");sleep(0.5)
    print("#                 $ $                       $$$$$$$  $   $  $     $  $$$$$$     $     $  $     $  $   $   $$$$                     #");sleep(0.5)
    print("#                 $ $                       $        $   $  $     $  $          $$   $$  $     $  $$  $  $                         #");sleep(0.5)
    print("#                 $ $                       $        $$$$$  $     $  $          $ $ $ $  $     $  $ $ $  $  $$$$$                  #");sleep(0.5)
    print("#                 $ $                       $        $   $  $     $  $          $  $  $  $     $  $  $$  $    $                    #");sleep(0.5)
    print("#                 $ $                       $$$$$$$  $   $  $$$$$$$  $$$$$$     $     $  $$$$$$$  $   $  $$$$$$                    #");sleep(0.5)
    print("#               $$$$$$$                                                                                                            #");sleep(0.5)
    print("#               $     $                                                                                                            #");sleep(0.5)
    print("#            $$$$$$$$$$$$                                                                                                          #");sleep(0.5)
    print("#            $          $                                   *******              *      *******                                    #");sleep(0.5)
    print("#       $$$$$$$$$$$$$$$$$$$$$$                              *     *             *             *                                    #");sleep(0.5)
    print("#       $                    $                              *     *            *              *                                    #");sleep(0.5)
    print("#       $                    $                              *******           *         *******                                    #");sleep(0.5)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          *     *          *                *                                    #");sleep(0.5)
    print("#    $                           $                          *     *         *                 *                                    #");sleep(0.5)
    print("#    $                           $                          *******        *            *******                                    #");sleep(0.5)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                                                                                 #");sleep(0.5)
    print("#                                                                                                                                  #");sleep(0.5)
    print("#                                                                                                                                  #");sleep(0.5)
    print("#                                                                                                                                  #");sleep(0.5)
    print("#                                                                \/   \/                                                               #");sleep(0.5)
    print("#                                                                $     $                                                             #");sleep(0.5)
    print("#                                                                $     $                                                #");sleep(0.5)
    print("#                                                                $     $                                       #");sleep(0.5)
    print("#                                                       $$$$$$$$$$$$$$$$$$$$$$                                                     #");sleep(0.5)
    print("#                                                      $         $     $    $$                                  #");sleep(0.5)
    print("#                                                     $$$$$$$              $$$$$$$$                                                      #");sleep(0.5)
    print("#                                                    $$     $$$$$$$$$$$$$$$$     $$                                                     #");sleep(0.5)
    print("#                                                    $$                          $$                                                    #");sleep(0.5)
    print("#           ☆*: *｡* o(≧▽≦)o *｡*:*☆                 $$                          $$                                                     #");sleep(0.5)
    print("#           (❁´◡`❁)                                $$                          $$                                                     #");sleep(0.5)
    print("#            ^_____^                             $$$ $$                          $$$$$$                                         #");sleep(0.5)
    print("#                                           $$$$$    $$                          $$   $$$                                              #");sleep(0.5)
    print("#                                          $$    $$$$$$$                               $$                                                 #");sleep(0.5)
    print("#                                          $$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                                                #");sleep(0.5)
    print("#                                          $$                                           $$$                                       #");sleep(0.5)
    print("#                                          $$                                           $$$                                        #");sleep(0.5)
    print("#                                          $$                                           $$$                                       #");sleep(0.5)
    print("#                                          $$$                                          $$$                                          #");sleep(0.5)
    print("#                                          $$$                                         $$$$                                            #");sleep(0.5)
    print("#                                          $$$                                         $$$$                                               #");sleep(0.5)
    print("#                                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                                                                 #");sleep(0.5)
    print("#                                                                                                                                  #");sleep(0.5)
    print("#####################################################################################################################################");sleep(0.5)
#turtle
    flower()
    screen=turtle.getscreen
    screen.mainloop()
        