a=input("Nhập ngày: ")
from time import sleep
if a=="8/3":
    sleep(0.5)
    print("###############################################################")
    print("#                                                             #");sleep(0.5)
    print("#                 $ $                   Chúc mừng 8/3         #");sleep(0.5)
    print("#                 $ $                   Chúc mừng 8/3         #");sleep(0.5)
    print("#                 $ $                   Chúc mừng 8/3         #");sleep(0.5)
    print("#                 $ $                   Chúc mừng 8/3         #");sleep(0.5)
    print("#                 $ $                   Chúc mừng 8/3         #");sleep(0.5)
    print("#               $$$$$$$                 Chúc mừng 8/3         #");sleep(0.5)
    print("#               $     $                 Chúc mừng 8/3         #");sleep(0.5)
    print("#            $$$$$$$$$$$$               Chúc mừng 8/3         #");sleep(0.5)
    print("#            $          $               Chúc mừng 8/3         #");sleep(0.5)
    print("#       $$$$$$$$$$$$$$$$$$$$$$                                #");sleep(0.5)
    print("#       $                    $                                #");sleep(0.5)
    print("#       $                    $                                #");sleep(0.5)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                            #");sleep(0.5)
    print("#    $                           $                            #");sleep(0.5)
    print("#    $                           $                            #");sleep(0.5)
    print("#    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                            #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("#           *******              *      *******               #");sleep(0.5)
    print("#           *     *             *             *               #");sleep(0.5)
    print("#           *     *            *              *               #");sleep(0.5)
    print("#           *******           *         *******               #");sleep(0.5)
    print("#           *     *          *                *               #");sleep(0.5)
    print("#           *     *         *                 *               #");sleep(0.5)
    print("#           *******        *            *******               #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("#           ☆*: *｡* o(≧▽≦)o *｡*:*☆                            #");sleep(0.5)
    print("#           (❁´◡`❁)                                           #");sleep(0.5)
    print("#            ^_____^                                          #");sleep(0.5)
    print("#                                                             #");sleep(0.5)
    print("###############################################################")
    


    import turtle
